# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058bf6f7a03e0a7d37398a38aa2c7b2d4c7dded3655a9c0a07d5ff7e1f9f708129fede8fbbf20df6b5478861b5321e8f66e2f830e61a971d10e50940e1ed02cf

test:
  secret_key_base: 1223ddd2b943f7893f408fa428682b62cdbcfe828f536f909182c978f2697c15f5e1e55af98e8204716bba29bddb3e2e68790c43ea4cde5a92889a8e6c58546a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
